import React from 'react';

const Privay = (props) => (
  <div className="tos-page">
    <div className="bui-padding">
      <h1>Privacy Policy</h1>
    </div>
    <div className="privacy-Text">
      <p>This Privacy Policy describes the information collected by Fang Media International Limited ("LiveTrading", "us", "we"), how that information may be used, with whom it may be shared, and your choices about such uses and disclosures. By using the website www.drfame.com (the "Site") and the services, features, content, applications or widgets, as well as mobile device applications offered by LiveTrading (collectively with the Site, the "Services"), you are accepting the practices described in this Privacy Policy. This Privacy Policy forms an integral part of LiveTrading's Terms of Service, which is incorporated by reference. Any capitalized term used but not defined in this Policy will have the meaning defined in the Terms of Service. Please read this Privacy Policy carefully when using the Services.</p>
      <h4>The Information LiveTrading May Collect</h4>
      <h4>Information You Provide</h4>
      <p>LiveTrading may collect and store any personal information you enter through the Services or the Site. This may include personally identifying	 information, such as your name, display name, username, e-mail address, phone number, address, location, gender, birthdate, pictures, social media accounts, and/or credit card or bank account information. If you are being considered to participate in the LiveTrading Partner Program, LiveTrading may also request certain additional information in order to verify your identity and/or comply with tax obligations, such as your government issued identification, a utility bill, and/or a completed IRS Form W-9. No system can be completely secure. Therefore, LiveTrading does not promise, and you should not expect, that such information may not be inadvertently collected and that such personal information will remain secure. </p><br /><br />
      <p>You also may give us permission to access your information on other services. If you connect to the Services using your Twitter, Facebook, Google, or other third-party service credentials (each, a "Supported Platform"), you authorize us to collect your authentication information, such as your display name, username, encrypted access credentials, and other information that may be available on or through your Supported Platform account, including but not limited to your name, pictures, and friends/followers lists. The information we get from Supported Platforms may depend on your settings or their privacy policies.</p> <br />
      <p>LiveTrading does not store any user financial information, even though we may request information about you and your credit card, bank account, and/or third party payment processor account. LiveTrading does not store certain financial data due to its use of third party agents as its financial transaction facilitator. Please refer to such third parties' Terms and Privacy Policies for more information about how these parties use your information. We do not store any user financial information, even though we may request information about yourself and your credit card and/or bank account. That financial information is handled, processed, and stored by the third party financial transaction processing companies. To the extent that LiveTrading uses third party providers for financial transaction services, we believe that such third parties take the privacy of your personal information seriously and will use your information only in accordance with the terms of their privacy policies.</p>
      <h4>Information Collected Automatically</h4>
      <p>Like many sites on the Internet, the Site automatically collects information from your browser when you visit the Site. This information includes your IP address, general location, browser type and language, access times, the content of any undeleted cookies that your browser previously accepted from LiveTrading (see "Cookies" below), and the referring website address. If you use LiveTrading's mobile application, LiveTrading may collect various non-identifying information, such as your mobile device type, device properties, device language, and IP address. LiveTrading may also collect various other information about your use of the Site and Services, such as your profile views, ad views, ad clicks, search queries, broadcast views, purchases, referral sources, crash reports, performance statistics, and other general usage statistics. We may use some of this automatically collected information to update your LiveTrading profile information, such as your location and language. We may also combine all of this non-identifying information with other non-identifying information to infer interests or demographic characteristics. In order for LiveTrading to work with your iPhone, iPad, Android phone, or other mobile device, LiveTrading must collect your Device Identification Code or "DIC". The DIC is a special type of identifier used in software applications in order to provide a unique reference number for applications like those used by your mobile device. Your DIC is not shared with other users.</p>
      <p>With your permission, we will access your location information from GPS-enabled devices that you have enabled or when you use location-based Services. If you choose to invite your contacts to use LiveTrading, with your authorization, we will access your contacts from your mobile device.
    </p>
     <h4>Cookies and Use of Cookie Data</h4>
     <p>Like many sites on the Internet, when you visit the Site, LiveTrading may assign your computer one or more cookies to facilitate access to the Site and to personalize your online experience. Through the use of a cookie, LiveTrading also may automatically collect information about your online activity on the Site, such as the web pages you visit, the time and date of your visits, the links you click, and the searches you conduct on the Site. LiveTrading may use this data to better understand how you interact with the Site, to monitor aggregate usage by our users and web traffic routing on the Site, and to improve the Site and our Services. Most browsers automatically accept cookies, but you can usually modify your browser setting to decline cookies. If you choose to decline cookies, please note that you may not be able to use some of the interactive features offered on the Site. In addition, please be aware that other parties may also place their own cookies on or through the Site, and may collect or solicit personal information from you. Other cookies may reflect de-identified demographic or other data linked to the registration data you have submitted to LiveTrading in hashed, non-human readable form. </p>
    <p>No personally identifiable information is contained in these cookies. Because there is not yet a consensus on how companies should respond to web browser-based or other do-not-track ("DNT") mechanisms, the Site does not respond to web browser-based DNT signals at this time.</p>
    <p>If you use LiveTrading's mobile device applications, LiveTrading may also use mobile cookies. A mobile cookie is a small data file transferred to your mobile device for record-keeping purposes. These mobile cookies help LiveTrading track session-based information and also better understand the effectiveness of the Services (by way of example only, by keeping track of the location and context in which you view a user profile). These mobile cookies do not contain any personally identifiable information.</p>
    <h4>Information Collected by Third Parties</h4>
    <p>LiveTrading may allow third parties, advertising companies, and ad networks to display advertisements on the Site and via the Services. These companies may use tracking technologies, such as cookies or pixel tags, to collect information about users who view or interact with their advertisements. LiveTrading does not provide any personal information to these third parties.</p> <br/>
    <p>If you connect your LiveTrading account to a Supported Platform, you may give LiveTrading permission to share your activity on the Services on the Supported Platform and/or to invite your friends/followers on the Supported Platform to the Services. You understand that such activities may be attributed to your account on Supported Platforms and may be published on the Supported Platforms.</p>
    <p>You understand and agree that Supported Platforms' or other third parties' use of information they collect from you is governed by their privacy policies, and LiveTrading's use of such information is governed by this Privacy Policy.</p>
    <h4>Agents</h4>
    <p>LiveTrading employs or engages other companies and individuals to perform business functions on behalf of the Site and Services. These persons are provided with personal identifying information required to perform their functions, but are prohibited by contract from using the information for other purposes. These persons engage in a variety of functions which include, but are not limited to, removing repetitive information from user lists, analyzing data, providing marketing assistance, processing credit card payments and providing user services.</p>
    <p>Any supplied billing information (if collected by and through the Site, as opposed to being directly inputted and collected by and through a third party payment processor) shall be encrypted for transmittal to a third party intermediary for processing. Such billing information is used only to bill you for those purchases you choose to make through the Site. The process is designed to protect your billing information against unauthorized misappropriation by third parties. As the technological landscape is constantly changing, no security system is absolutely secure. LiveTrading cannot and does not guarantee the security of any of its databases and information contained therein, nor can LiveTrading guarantee any supplied information will be absolutely secure from interception during transmission to the Site over the Internet.</p>
    <h4>How LiveTrading Uses the Information It Collects</h4>
    <p>LiveTrading may use information that it collects as described above to:
    <ul>
      <li className="list_heading">
      deliver the services that you have requested.
      </li>
      <li className="list_heading">
      provide you with customer support.
      </li>
      <li className="list_heading">
      improve the Site and Services.
      </li>
      <li className="list_heading">
      enforce or exercise any rights in LiveTrading's Terms of Service.
      </li>
      <li className="list_heading">
      perform functions as otherwise described to you at the time of collection.

      </li>
    </ul>
    </p>
    <p>LiveTrading may also release your personal information to a third-party in order to protect, establish, or exercise our legal rights or defend against legal claims; comply with a subpoena, court order, legal process, or other legal requirement; in connection with a merger, acquisition, bankruptcy, dissolution, reorganization, or similar transactions or proceedings we may engage in that involves the transfer of the information described in this Privacy Policy; when we believe in good faith that such disclosure is necessary to comply with the law, prevent imminent physical harm or financial loss; or investigate, prevent, or take action regarding illegal activities, suspected fraud, threats to our property, or as necessary or appropriate in connection with an investigation of fraud, intellectual property infringement, piracy, or other unlawful activity.</p>
    <p>Please note that to the extent you include any personal information in any content you upload to the Site and/or Services, we have the right to publish that content in connection with the operation of the Site and Services.</p>
    <p>Through your settings within the Site and Services, you can choose which communications you receive from us, manage your public profile information, and set your sharing preferences.</p>
    <h4>Public Spaces</h4>
    <p>LiveTrading is a community. We offer several features that allow users to connect and communicate in public or semi-public spaces. Please use common sense and good judgment when posting in these public spaces or sharing your personal information with other users on LiveTrading. Be aware that any personal information you submit there can be read, seen, heard, collected, or used by others, or could be used to send you unsolicited messages or for any other purposes. Some information you share on your LiveTrading profile or in public spaces may be accessible by general users of the Internet, not just other LiveTrading users. You are solely responsible for the personal information you choose to post in public spaces on LiveTrading. We do not control any such uses of your personal information, and by using the Services you acknowledge and assume the risk that any personal information you provide may be viewed and used by third parties in any manner. LiveTrading generally does not remove content from public spaces, and your posts or other content may remain public after your account is closed.</p>
    <h4>Third-Party Websites</h4>
    <span class="bold">Children's Privacy
      LiveTrading forbids the use of the Site and Services to individuals under the age of 13, without the consent of a parent or guardian. LiveTrading does not knowingly collect personal information from children under the age of 13. If LiveTrading learns that the Site or Services have collected personally identifiable information of children under the age of 13, we will take the appropriate steps to delete this information.
    </span>
    <br/>
    <br/>
    <h4>Notice to California Users</h4>
    <p>Subject to the limitations under California Civil Code § 1798.83, if you are a California resident, you may ask us to provide you with a list of certain categories of personal information that we have disclosed to third parties for their direct marketing purposes during the immediately preceding calendar year. You may also request the identity of certain third parties that received your personal information from us for their direct marketing purposes during the immediately preceding calendar year. You may make a request as described hereinabove once a year. LiveTrading does not currently disclose personal information to third parties for their direct marketing purposes.</p>
    <h4>Data Processing</h4>
    <p>This Privacy Policy is intended to cover collection of information on the Site and/or Services from residents of the United States. Irrespective of the country you are using the Site or Services from, please be aware that your information may be transferred to, stored, and processed in the United States or any other jurisdiction. The laws and rules that protect your data and privacy rights in those jurisdictions may vary from those of where you are located, such as when the government may access your data.</p>
    <p>By using the Site or Services, you understand that your information may be transferred to LiveTrading's facilities and those third parties with whom LiveTrading shares it as described in this Privacy Policy. You are responsible for ensuring that information you share conforms to all local data protection laws.</p>
    <h4>Changes to the Privacy Policy</h4>
    <p>LiveTrading will occasionally update this Privacy Policy. When LiveTrading posts changes to this Privacy Policy, it will revise the date at the top of this Privacy Policy. If we make material changes to this Privacy Policy, we will notify you by email or by posting a notice on the Services prior to the effective date of the changes. LiveTrading recommends that you check the Services from time to time to inform yourself of any changes in this Privacy Policy or any of LiveTrading's other policies.</p>
    </div>
  </div>
);

export default Privay;
