export default `
    query findBroadcaster ($uid: ID!){
        findBroadcaster(uid: $uid) {
          uid
          name
          image
          aboutme
          follower
          following
          online
          location
          followers{
            uid
            name
            image
            aboutme
            follower
            following
            online
            location
          }
          followings{
            uid
            name
            image
            aboutme
            follower
            following
            online
            location
          }
          broadcaster{
            views
            created
            rP
            rN
            totalVideos
          }
          broadcasterDetail{
            lastPublished
            lastStartPublishing
            playUrl
            playbackId
            lastPlayback{
              uid
              userId
              title
              cover
              lastUpdated
              title
              views
              liveViews
            }
          }
          playbacks {
            uid
            userId
            title
            cover
            lastUpdated
            title
            views
            url
            liveViews
          }
        }
      }
`;
